name: Publish

on:
  push:
    branches: [ vsix ]
  pull_request:
    branches: [ vsix ]

env:
  dotnet_sdk_version: '3.1.x'
  postgis_version: 4
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6
        with:
          nuget-version: latest
        
      - name: Restore NuGet Packages for Npgsql
        run: nuget restore src\Npgsql\Npgsql.csproj

      - name: Restore NuGet Packages for VSIX
        run: nuget restore src\VSIX\VSIX.csproj

      - name: Create Npgsql
        run: msbuild src\Npgsql\Npgsql.csproj -p:Configuration=Release -v:Minimal

      - name: Create VSIX
        run: msbuild src\VSIX\VSIX.csproj -p:Configuration=Release -v:Minimal

      - name: Upload artifacts (vsix)
        uses: actions/upload-artifact@v1
        with:
          name: Npgsql.vsix
          path: src/VSIX/bin/Release/Npgsql.vsix
